---
kind: template
load: docker_image.yaml
trigger:
  branch:
    - main
data:
  tags:
    - ${DRONE_BRANCH}
    - latest
---
kind: template
load: docker_image.yaml
trigger:
  event:
    - tag
data:
  tags:
    - ${DRONE_TAG}
    - ${DRONE_SEMVER_MAJOR}
    - ${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}
    - ${DRONE_SEMVER}
    - latest
