---
kind: pipeline
name: versioned_docker
type: docker
trigger:
  event:
    - tag
steps:
  - name: build and publish container image
    image: plugins/docker
    settings:
      registry: git.snyssen.be
      username: ${DRONE_COMMIT_AUTHOR}
      password:
        from_secret: gitea_access_token
      repo: "git.snyssen.be/${DRONE_REPO}"
      tags:
        - ${DRONE_SEMVER_MAJOR}
        - ${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}
        - ${DRONE_SEMVER}
        - latest
---
kind: pipeline
name: main_docker
type: docker
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: build and publish container image
    image: plugins/docker
    settings:
      registry: git.snyssen.be
      username: ${DRONE_COMMIT_AUTHOR}
      password:
        from_secret: gitea_access_token
      repo: "git.snyssen.be/${DRONE_REPO}"
      tags:
        - ${DRONE_BRANCH}
        - latest
